### PR TITLE
Add regions query param to document entities response

### PR DESCRIPTION
**Pull request by pbrzostowski**
Add information about optional `regions` parameter to get document entities regions

Note: Some updates in packages because npm returns vulnerability error.

### CODE REVIEW

**Comment by pbrzostowski** [comment]
Added

**Comment by levrik** [comment]
@pbrzostowski Just examples? Or was `region` already part of the model?

**Comment by pbrzostowski** [comment]
@levrik not sure what do you mean? I can see regions are rendered in a documentation Response. Is that what you mean?

**Comment by levrik** [comment]
@pbrzostowski 

image

Model definition doesn't define `region`?

**Comment by pbrzostowski** [comment]
This PR is adding it. This is a render from my local:

Screenshot 2023-05-11 at 14 36 32

**Comment by levrik** [comment]
@pbrzostowski Oh, true. Not sure what I saw there yesterday 😅

**Review by levrik — APPROVED** [review]

**Pull request merged**
